package de.htwg.se.ninja.controller.component

object State extends Enumeration {

  type state = Value
  val
  INSERTING_NAME_1,
  INSERTING_NAME_2,
  SET_FLAG_1,
  SET_FLAG_2,
  SET_FLAG_1_FAILED,
  SET_FLAG_2_FAILED,
  NAME_REGEX_INCORRECT_1,
  NAME_REGEX_INCORRECT_2,
  FLAG_REGEX_INCORRECT_1,
  FLAG_REGEX_INCORRECT_2,
  WALKED_INPUT_INCORRECT,
  WALK_REGEX_INCORRECT,
  No_NINJA_OR_NOT_VALID,
  DIRECTION_DOES_NOT_EXIST,
  TURN,
  WALKED,
  WON = Value
}
